# Generated by Django 6.0.4 on 2026-04-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aboutimage_aboutvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='campus_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='history_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
