# Generated by Django 6.0.4 on 2026-08-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aboutpage_campus_image_aboutpage_history_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='extra_details',
            field=models.TextField(blank=True, help_text='Additional listing details (e.g., landmarks, access roads)'),
        ),
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(blank=True, help_text='Location or nearest town', max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='plot_size',
            field=models.CharField(default='50 x 100', max_length=50),
        ),
    ]
