# Generated by Django 6.0.4 on 2026-08-17 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course_extra_details_course_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='intake_period',
        ),
    ]
