# Generated by Django 5.0.3 on 2026-08-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_courseimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('main-view', 'Main View'), ('frontage', 'Frontage'), ('road-access', 'Road Access'), ('plot-layout', 'Plot Layout'), ('surroundings', 'Surroundings'), ('title-documents', 'Title Documents'), ('other', 'Other')], max_length=20),
        ),
    ]
