# Generated by Django 6.0.4 on 2026-08-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_galleryimage_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('youtube_url', models.URLField(help_text='Full YouTube URL (https://www.youtube.com/watch?v=...)')),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.URLField(blank=True, help_text='Optional thumbnail URL (auto-extracted if left blank)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
