# Generated by Django 6.0.4 on 2026-08-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelasabiliInventory',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='ProductName', max_length=255)),
            ],
            options={
                'verbose_name': 'Helasabili Inventory Item',
                'verbose_name_plural': 'Helasabili Inventory Items',
                'db_table': 'Inventories',
                'managed': False,
            },
        ),
    ]
